# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
