# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170730_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='temp data', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='temp_data', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='+639171234567', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel_no',
            field=models.CharField(default='029111111', max_length=10),
            preserve_default=False,
        ),
    ]
