# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
