# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20170525_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='event_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
