# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_registry_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
