# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_registry_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.TextField(max_length=1000),
        ),
    ]
