# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20170528_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='bought_by',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
