# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20170528_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryitem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='registry',
            name='address',
            field=models.CharField(default='123 Fake St.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='baby_birthdate',
            field=models.DateField(blank=True, default=datetime.date(2017,1,1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='delivered_where',
            field=models.CharField(default='address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2017,1,1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='event_venue',
            field=models.CharField(default='123 Fake St.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='name_baby',
            field=models.CharField(default='baby', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='name_father',
            field=models.CharField(default='father', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='name_mother',
            field=models.CharField(default='mother', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registryitem',
            name='img_url',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registryitem',
            name='item_url',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registryitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
