# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20170723_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
