# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 15:59
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_auto_20170723_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id'),
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id'),
        ),
    ]
