# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20170723_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryitem',
            name='item',
        ),
    ]
