# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_remove_registryitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitem',
            name='item_notes',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
