# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_registryitem_item_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
