# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20170729_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitem',
            name='quantity_bought',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='bought_by',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registryitem',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
