# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20170729_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='item_url',
            field=models.TextField(max_length=300),
        ),
    ]
