# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_auto_20170729_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='delivered_where',
            field=models.CharField(choices=[('venue', 'Venue'), ('address', 'Home Address')], max_length=30),
        ),
    ]
